name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /var/www/tatamata
          git pull origin master
          composer install --no-dev --no-interaction
          sudo chown -R www-data:www-data /var/www/tatamata
          sudo chmod -R 755 /var/www/tatamata
